apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v6
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
      #通过tolerations将pod部署到master节点（已通过kubectl taint nodes k8s-mst node-role.kubernetes.io/master="true":NoSchedule命令为master节点添加污点）
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"node-role.kubernetes.io/master", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]'
    spec:
      #配合taints使用，pods只能部署到master节点
      nodeSelector:
        kubernetes.io/hostname: k8s-mst

      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/lvpengze/heapster:canary
        name: heapster
        command:
        - /heapster
        #api-server的地址
        - --source=kubernetes:http://192.168.0.10:8080?inClusterConfig=false
        - --sink=influxdb:http://10.254.0.4:8086