apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-grafana
  namespace: kube-system
  labels:
    k8s-app: influxGrafana
  #selfLink: /api/v1/namespaces/kube-system/replicationcontrollers/influxdb-grafana
spec:
  replicas: 1
  selector:
    k8s-app: influxGrafana
  template:
    metadata:
      labels:
        k8s-app: influxGrafana
    spec:
      containers:
      - image: kubernetes/heapster_influxdb:v0.5
        name: influxdb
        volumeMounts:
        - name: influxdb-storage
          mountPath: /data

      - image: docker.io/xiechengsheng/heapster-grafana-amd64:v4.0.2
        name: grafana
        env:
        #api-server的地址
        - name: INFLUXDB_SERVICE_URL
          value: http://10.254.0.4:8086
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - emptyDir: {}
        name: influxdb-storage
      - emptyDir: {}
        name: grafana-storage