apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-grafana
  namespace: kube-system
  labels:
    k8s-app: influxGrafana
spec:
  replicas: 1
  selector:
    k8s-app: influxGrafana
  template:
    metadata:
      labels:
        k8s-app: influxGrafana
      #通过tolerations将pod部署到master节点（已通过kubectl taint nodes k8s-mst node-role.kubernetes.io/master="true":NoSchedule命令为master节点添加污点）
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"node-role.kubernetes.io/master", "operator":"Equal", "value":"true", "effect":"NoSchedule"}]'
    spec:
      #配合taints使用，pods只能部署到master节点
      nodeSelector:
        kubernetes.io/hostname: k8s-mst

      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/lvpengze/heapster_influxdb:v0.5
        name: influxdb
        volumeMounts:
        - name: influxdb-storage
          mountPath: /data

      - image: registry.cn-hangzhou.aliyuncs.com/lvpengze/heapster-grafana-amd64:v4.0.2
        name: grafana
        env:
        #api-server的地址
        - name: INFLUXDB_SERVICE_URL
          value: http://10.254.0.4:8086
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - emptyDir: {}
        name: influxdb-storage
      - emptyDir: {}
        name: grafana-storage