apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v6
  #selfLink: /api/v1/namespaces/kube-system/replicationcontrollers/heapster
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - image: kubernetes/heapster:canary
        name: heapster
        command:
        - /heapster
        #api-server的地址
        - --source=kubernetes:http://192.168.0.10:8080?inClusterConfig=false
        - --sink=influxdb:http://10.254.0.4:8086